---
title: "Explore the Plays"
author: "Amit Kapoor"
date: "6 July 2015"
output: html_document
---

Lets start exploring the data and see if we can see some trends, patterns and even exceptions.

```{r}
# Load the data and libraries
library(dplyr)
library(ggplot2)
library(scales)
library(lubridate)

plays <- read.csv("data/tweets_processed.csv")
plays$created <- ymd_hms(plays$created)
```

Top 10 plays by artist
```{r}
# Top Plays by artist
plays.artist <- plays %>%
                group_by(artist) %>%
                summarize(count = n()) %>%
                arrange(desc(count))
plays.artist
```

Top plays by song
```{r}
# Top Plays by song & artist
plays.song  <- plays %>%
                   group_by(songartist) %>%
                   summarize(song.count = n()) %>%
                   ungroup() %>%
                   arrange(desc(song.count))
plays.song
```

Lets plot this and start to see...

```{r}
# Spread of the plays
ggplot(plays.song) + aes(song.count) + geom_histogram(binwidth = 1)

# Top 20 most played songs
plays.top25 <- plays.song[1:20,]
plays.count25 <- inner_join(plays, plays.top25,
                                  by = "songartist")
write.csv(plays.count25, "dataset.csv", row.names = FALSE)

# Top 20 most played songs - when?
ggplot(plays.count25) + 
  aes(x = created, y = reorder(songartist, song.count)) +
  geom_point(size = 5, alpha = 0.75) + 
  scale_x_datetime() + 
  xlab("Day") + ylab("Song - Artist")


# Top 40 songs played
plays.top40 <- plays.song[1:40,]
plays.rest40 <- plays.song[-(1:40),]

# Sample Stats 

total.songs <- dim(plays.song)[1]
total.plays <- dim(plays)[1]
total.plays.top40 <- sum(plays.top40$song.count)
total.plays.rest40 <- sum(plays.rest40$song.count)

total.songs
total.plays
total.plays.top40
total.plays.rest40
total.plays.top40 + total.plays.rest40

```


















